// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace OptimalEducation.DAL.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class ExamType3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ExamType3));
        
        string IMigrationMetadata.Id
        {
            get { return "201405241931275_ExamType3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
