// <auto-generated />
namespace OptimalEducation.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class AddCharacteristicEnum_Into_Characteristics : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddCharacteristicEnum_Into_Characteristics));
        
        string IMigrationMetadata.Id
        {
            get { return "201404221055052_AddCharacteristicEnum_Into_Characteristics"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
