// <auto-generated />
namespace OptimalEducation.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class ExamType2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ExamType2));
        
        string IMigrationMetadata.Id
        {
            get { return "201405241925208_ExamType2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
