// <auto-generated />
namespace OptimalEducation.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class ResultCanBeEmpty : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ResultCanBeEmpty));
        
        string IMigrationMetadata.Id
        {
            get { return "201404220719193_ResultCanBeEmpty"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
