// <auto-generated />
namespace OptimalEducation.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class EducationFormEnum : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EducationFormEnum));
        
        string IMigrationMetadata.Id
        {
            get { return "201405220909274_EducationFormEnum"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
