// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace OptimalEducation.DAL.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class HeiFullName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(HeiFullName));
        
        string IMigrationMetadata.Id
        {
            get { return "201405202226447_HEIFullName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
