// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace OptimalEducation.DAL.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class SchoolMarkCanBeNull : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SchoolMarkCanBeNull));
        
        string IMigrationMetadata.Id
        {
            get { return "201404220724563_SchoolMarkCanBeNull"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
