// <auto-generated />
namespace OptimalEducation.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class Change_OlympiadResult : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Change_OlympiadResult));
        
        string IMigrationMetadata.Id
        {
            get { return "201403101311081_Change_OlympiadResult"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
