// <auto-generated />
namespace OptimalEducation.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class fix_type : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fix_type));
        
        string IMigrationMetadata.Id
        {
            get { return "201403161633589_fix_type"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
