SET IDENTITY_INSERT [dbo].[HigherEducationInstitutions] ON
INSERT INTO [dbo].[HigherEducationInstitutions] ([Id], [Name], [Prestige], [CityId], [Type], [FullName]) VALUES (2, N'МГУ', 99, 2, 0, N'Московский государственный университет им. М. В. Ломоносова')
INSERT INTO [dbo].[HigherEducationInstitutions] ([Id], [Name], [Prestige], [CityId], [Type], [FullName]) VALUES (3, N'СПбГУ', 91, 3, 0, N'Санкт-Петербургский государственный политехнический университет')
INSERT INTO [dbo].[HigherEducationInstitutions] ([Id], [Name], [Prestige], [CityId], [Type], [FullName]) VALUES (4, N'МГТУ', 98, 2, 0, N'Московский государственный технический университет им. Н. Э. Баумана')
INSERT INTO [dbo].[HigherEducationInstitutions] ([Id], [Name], [Prestige], [CityId], [Type], [FullName]) VALUES (5, N'МФТИ', 96, 2, 0, N'Московский физико-технический институт')
INSERT INTO [dbo].[HigherEducationInstitutions] ([Id], [Name], [Prestige], [CityId], [Type], [FullName]) VALUES (6, N'МИФИ', 93, 2, 0, N'Национальный исследовательский ядерный университет "МИФИ"')
INSERT INTO [dbo].[HigherEducationInstitutions] ([Id], [Name], [Prestige], [CityId], [Type], [FullName]) VALUES (7, N'ВШЭ ', 95, 2, 0, N'Высшая школа экономики')
INSERT INTO [dbo].[HigherEducationInstitutions] ([Id], [Name], [Prestige], [CityId], [Type], [FullName]) VALUES (8, N'МЭИ', 94, 2, 0, N'Московский энергетический институт')
INSERT INTO [dbo].[HigherEducationInstitutions] ([Id], [Name], [Prestige], [CityId], [Type], [FullName]) VALUES (9, N'ТПУ', 92, 5, 0, N'Томский политехнический университет')
INSERT INTO [dbo].[HigherEducationInstitutions] ([Id], [Name], [Prestige], [CityId], [Type], [FullName]) VALUES (10, N'НГУ', 90, 6, 0, N'Новосибирский государственный университет')
INSERT INTO [dbo].[HigherEducationInstitutions] ([Id], [Name], [Prestige], [CityId], [Type], [FullName]) VALUES (11, N'МГИМО', 89, 2, 0, N'Московский государственный институт международных отношений')
INSERT INTO [dbo].[HigherEducationInstitutions] ([Id], [Name], [Prestige], [CityId], [Type], [FullName]) VALUES (12, N'СФУ', 88, 7, 0, N'Сибирский федеральный университет')
INSERT INTO [dbo].[HigherEducationInstitutions] ([Id], [Name], [Prestige], [CityId], [Type], [FullName]) VALUES (13, N'РГУНиГ', 87, 2, 0, N'Российский государственный университет нефти и газа')
INSERT INTO [dbo].[HigherEducationInstitutions] ([Id], [Name], [Prestige], [CityId], [Type], [FullName]) VALUES (14, N'Финуниверситет', 86, 2, 0, N'Финансовый университет при Правительстве РФ')
INSERT INTO [dbo].[HigherEducationInstitutions] ([Id], [Name], [Prestige], [CityId], [Type], [FullName]) VALUES (15, N'ТГУ', 85, 5, 0, N'Томский государственный университет')
INSERT INTO [dbo].[HigherEducationInstitutions] ([Id], [Name], [Prestige], [CityId], [Type], [FullName]) VALUES (16, N'КФУ', 84, 9, 0, N'Казанский (Приволжский) федеральный университет')
INSERT INTO [dbo].[HigherEducationInstitutions] ([Id], [Name], [Prestige], [CityId], [Type], [FullName]) VALUES (17, N'УрФУ', 81, 4, 0, N'Уральский федеральный университет ')
INSERT INTO [dbo].[HigherEducationInstitutions] ([Id], [Name], [Prestige], [CityId], [Type], [FullName]) VALUES (18, N'ИТМО', 77, 3, 0, N'Санкт-Петербургский государственный университет информационных технологий, механики и оптики')
INSERT INTO [dbo].[HigherEducationInstitutions] ([Id], [Name], [Prestige], [CityId], [Type], [FullName]) VALUES (19, N'КНИТУ', 75, 9, 0, N'Казанский технологический университет')
INSERT INTO [dbo].[HigherEducationInstitutions] ([Id], [Name], [Prestige], [CityId], [Type], [FullName]) VALUES (20, N'ПСПбГМУ', 70, 3, 0, N'Санкт-Петербургский государственный медицинский университет им. акад. И. П. Павлова')
INSERT INTO [dbo].[HigherEducationInstitutions] ([Id], [Name], [Prestige], [CityId], [Type], [FullName]) VALUES (21, N'ИНЖЭКОН', 59, 3, 0, N'Санкт-Петербургский государственный инженерно-экономический университет')
INSERT INTO [dbo].[HigherEducationInstitutions] ([Id], [Name], [Prestige], [CityId], [Type], [FullName]) VALUES (22, N'ГУАП', 48, 3, 0, N'Санкт-Петербургский государственный университет аэрокосмического приборостроения')
INSERT INTO [dbo].[HigherEducationInstitutions] ([Id], [Name], [Prestige], [CityId], [Type], [FullName]) VALUES (23, N'УрГЮА', 36, 4, 0, N'Уральская государственная юридическая академия')
SET IDENTITY_INSERT [dbo].[HigherEducationInstitutions] OFF
