SET IDENTITY_INSERT [dbo].[EducationLineRequirements] ON
INSERT INTO [dbo].[EducationLineRequirements] ([Id], [Requirement], [EducationLineId], [ExamDisciplineId]) VALUES (4, 83, 5, 1)
INSERT INTO [dbo].[EducationLineRequirements] ([Id], [Requirement], [EducationLineId], [ExamDisciplineId]) VALUES (5, 71, 5, 2)
INSERT INTO [dbo].[EducationLineRequirements] ([Id], [Requirement], [EducationLineId], [ExamDisciplineId]) VALUES (7, 62, 5, 3)
INSERT INTO [dbo].[EducationLineRequirements] ([Id], [Requirement], [EducationLineId], [ExamDisciplineId]) VALUES (9, 73, 6, 1)
INSERT INTO [dbo].[EducationLineRequirements] ([Id], [Requirement], [EducationLineId], [ExamDisciplineId]) VALUES (10, 89, 6, 2)
INSERT INTO [dbo].[EducationLineRequirements] ([Id], [Requirement], [EducationLineId], [ExamDisciplineId]) VALUES (11, 69, 6, 3)
INSERT INTO [dbo].[EducationLineRequirements] ([Id], [Requirement], [EducationLineId], [ExamDisciplineId]) VALUES (12, 76, 7, 1)
INSERT INTO [dbo].[EducationLineRequirements] ([Id], [Requirement], [EducationLineId], [ExamDisciplineId]) VALUES (13, 73, 7, 2)
INSERT INTO [dbo].[EducationLineRequirements] ([Id], [Requirement], [EducationLineId], [ExamDisciplineId]) VALUES (14, 64, 7, 4)
INSERT INTO [dbo].[EducationLineRequirements] ([Id], [Requirement], [EducationLineId], [ExamDisciplineId]) VALUES (15, 59, 8, 1)
INSERT INTO [dbo].[EducationLineRequirements] ([Id], [Requirement], [EducationLineId], [ExamDisciplineId]) VALUES (16, 63, 8, 2)
INSERT INTO [dbo].[EducationLineRequirements] ([Id], [Requirement], [EducationLineId], [ExamDisciplineId]) VALUES (17, 67, 8, 6)
INSERT INTO [dbo].[EducationLineRequirements] ([Id], [Requirement], [EducationLineId], [ExamDisciplineId]) VALUES (18, 87, 4, 1)
INSERT INTO [dbo].[EducationLineRequirements] ([Id], [Requirement], [EducationLineId], [ExamDisciplineId]) VALUES (19, 82, 4, 2)
INSERT INTO [dbo].[EducationLineRequirements] ([Id], [Requirement], [EducationLineId], [ExamDisciplineId]) VALUES (20, 76, 4, 3)
SET IDENTITY_INSERT [dbo].[EducationLineRequirements] OFF
