SET IDENTITY_INSERT [dbo].[Faculties] ON
INSERT INTO [dbo].[Faculties] ([Id], [Name], [Prestige], [HigherEducationInstitutionId]) VALUES (1, N'default_department', 100, 1)
INSERT INTO [dbo].[Faculties] ([Id], [Name], [Prestige], [HigherEducationInstitutionId]) VALUES (2, N'ПМ-ПУ', 70, 3)
INSERT INTO [dbo].[Faculties] ([Id], [Name], [Prestige], [HigherEducationInstitutionId]) VALUES (3, N'МАТМЕХ', 85, 3)
INSERT INTO [dbo].[Faculties] ([Id], [Name], [Prestige], [HigherEducationInstitutionId]) VALUES (4, N'Филологический', 75, 3)
INSERT INTO [dbo].[Faculties] ([Id], [Name], [Prestige], [HigherEducationInstitutionId]) VALUES (5, N'МЕХМАТ', 90, 2)
INSERT INTO [dbo].[Faculties] ([Id], [Name], [Prestige], [HigherEducationInstitutionId]) VALUES (6, N'Филологический', 75, 2)
INSERT INTO [dbo].[Faculties] ([Id], [Name], [Prestige], [HigherEducationInstitutionId]) VALUES (7, N'Юридический', 80, 2)
INSERT INTO [dbo].[Faculties] ([Id], [Name], [Prestige], [HigherEducationInstitutionId]) VALUES (8, N'Факультет вычислительной математики и кибернетики', 80, 2)
INSERT INTO [dbo].[Faculties] ([Id], [Name], [Prestige], [HigherEducationInstitutionId]) VALUES (9, N'Физический факультет', 80, 2)
INSERT INTO [dbo].[Faculties] ([Id], [Name], [Prestige], [HigherEducationInstitutionId]) VALUES (10, N'Химический факультет', 80, 2)
INSERT INTO [dbo].[Faculties] ([Id], [Name], [Prestige], [HigherEducationInstitutionId]) VALUES (11, N'Факультет биоинженерии и биоинформатики', 70, 2)
INSERT INTO [dbo].[Faculties] ([Id], [Name], [Prestige], [HigherEducationInstitutionId]) VALUES (12, N'Географический факультет', 70, 2)
INSERT INTO [dbo].[Faculties] ([Id], [Name], [Prestige], [HigherEducationInstitutionId]) VALUES (13, N'Факультет искусств', 65, 2)
INSERT INTO [dbo].[Faculties] ([Id], [Name], [Prestige], [HigherEducationInstitutionId]) VALUES (14, N'Факультет политологии', 65, 2)
INSERT INTO [dbo].[Faculties] ([Id], [Name], [Prestige], [HigherEducationInstitutionId]) VALUES (15, N'Факультет психологии', 65, 3)
INSERT INTO [dbo].[Faculties] ([Id], [Name], [Prestige], [HigherEducationInstitutionId]) VALUES (16, N'Факультет социологии', 65, 3)
INSERT INTO [dbo].[Faculties] ([Id], [Name], [Prestige], [HigherEducationInstitutionId]) VALUES (17, N'Институт истории', 70, 3)
INSERT INTO [dbo].[Faculties] ([Id], [Name], [Prestige], [HigherEducationInstitutionId]) VALUES (18, N'Журналистики', 80, 3)
INSERT INTO [dbo].[Faculties] ([Id], [Name], [Prestige], [HigherEducationInstitutionId]) VALUES (19, N'Радиоэлектроника и лазерная техника', 70, 4)
INSERT INTO [dbo].[Faculties] ([Id], [Name], [Prestige], [HigherEducationInstitutionId]) VALUES (20, N'Машиностроительные технологии', 75, 4)
INSERT INTO [dbo].[Faculties] ([Id], [Name], [Prestige], [HigherEducationInstitutionId]) VALUES (21, N'Биомедицинская техника', 65, 4)
INSERT INTO [dbo].[Faculties] ([Id], [Name], [Prestige], [HigherEducationInstitutionId]) VALUES (22, N'Инженерный бизнес и менеджмент', 70, 4)
INSERT INTO [dbo].[Faculties] ([Id], [Name], [Prestige], [HigherEducationInstitutionId]) VALUES (23, N'Лингвистика', 75, 4)
INSERT INTO [dbo].[Faculties] ([Id], [Name], [Prestige], [HigherEducationInstitutionId]) VALUES (24, N'Факультет радиотехники и кибернетики', 75, 5)
INSERT INTO [dbo].[Faculties] ([Id], [Name], [Prestige], [HigherEducationInstitutionId]) VALUES (25, N'Факультет общей и прикладной физики ', 70, 5)
INSERT INTO [dbo].[Faculties] ([Id], [Name], [Prestige], [HigherEducationInstitutionId]) VALUES (26, N'Факультет физической и квантовой электроники', 70, 5)
INSERT INTO [dbo].[Faculties] ([Id], [Name], [Prestige], [HigherEducationInstitutionId]) VALUES (27, N'Факультет инноваций и высоких технологий', 65, 5)
INSERT INTO [dbo].[Faculties] ([Id], [Name], [Prestige], [HigherEducationInstitutionId]) VALUES (28, N'Факультет бизнес-информатики', 75, 7)
INSERT INTO [dbo].[Faculties] ([Id], [Name], [Prestige], [HigherEducationInstitutionId]) VALUES (29, N'Факультет менеджмента', 75, 7)
INSERT INTO [dbo].[Faculties] ([Id], [Name], [Prestige], [HigherEducationInstitutionId]) VALUES (30, N'Факультет логистики', 70, 7)
INSERT INTO [dbo].[Faculties] ([Id], [Name], [Prestige], [HigherEducationInstitutionId]) VALUES (31, N'Банковский институт', 75, 7)
INSERT INTO [dbo].[Faculties] ([Id], [Name], [Prestige], [HigherEducationInstitutionId]) VALUES (32, N'Отделение статистики, анализа данных и демографии', 65, 7)
INSERT INTO [dbo].[Faculties] ([Id], [Name], [Prestige], [HigherEducationInstitutionId]) VALUES (33, N'Институт электротехники', 70, 8)
INSERT INTO [dbo].[Faculties] ([Id], [Name], [Prestige], [HigherEducationInstitutionId]) VALUES (34, N'Гуманитарно-прикладной институт', 65, 8)
INSERT INTO [dbo].[Faculties] ([Id], [Name], [Prestige], [HigherEducationInstitutionId]) VALUES (35, N'Институт автоматики и вычислительной техники', 75, 8)
INSERT INTO [dbo].[Faculties] ([Id], [Name], [Prestige], [HigherEducationInstitutionId]) VALUES (41, N'Гуманитарный', 70, 18)
INSERT INTO [dbo].[Faculties] ([Id], [Name], [Prestige], [HigherEducationInstitutionId]) VALUES (42, N'Естественнонаучный', 70, 18)
INSERT INTO [dbo].[Faculties] ([Id], [Name], [Prestige], [HigherEducationInstitutionId]) VALUES (43, N'Инженерно-физический', 70, 18)
INSERT INTO [dbo].[Faculties] ([Id], [Name], [Prestige], [HigherEducationInstitutionId]) VALUES (44, N'Точной механики и технологий', 75, 18)
INSERT INTO [dbo].[Faculties] ([Id], [Name], [Prestige], [HigherEducationInstitutionId]) VALUES (45, N'Фотоники и оптоинформатики', 60, 18)
INSERT INTO [dbo].[Faculties] ([Id], [Name], [Prestige], [HigherEducationInstitutionId]) VALUES (46, N'Институт аэрокосмических приборов и систем', 70, 22)
INSERT INTO [dbo].[Faculties] ([Id], [Name], [Prestige], [HigherEducationInstitutionId]) VALUES (47, N'Институт радиотехники, электроники и связи', 60, 22)
INSERT INTO [dbo].[Faculties] ([Id], [Name], [Prestige], [HigherEducationInstitutionId]) VALUES (48, N'Юридический факультет', 65, 22)
INSERT INTO [dbo].[Faculties] ([Id], [Name], [Prestige], [HigherEducationInstitutionId]) VALUES (49, N'ФАКУЛЬТЕТ ИНФОРМАЦИОННЫХ СИСТЕМ В ЭКОНОМИКЕ И УПРАВЛЕНИИ', 75, 21)
INSERT INTO [dbo].[Faculties] ([Id], [Name], [Prestige], [HigherEducationInstitutionId]) VALUES (50, N'ФАКУЛЬТЕТ ЭКОНОМИКИ И УПРАВЛЕНИЯ В ХИМИЧЕСКОЙ ПРОМЫШЛЕННОСТИ И ПРИРОДОПОЛЬЗОВАНИИ', 70, 21)
INSERT INTO [dbo].[Faculties] ([Id], [Name], [Prestige], [HigherEducationInstitutionId]) VALUES (51, N'ФАКУЛЬТЕТ ПРЕДПРИНИМАТЕЛЬСТВА И ФИНАНСОВ', 75, 21)
INSERT INTO [dbo].[Faculties] ([Id], [Name], [Prestige], [HigherEducationInstitutionId]) VALUES (52, N'ГУМАНИТАРНЫЙ ФАКУЛЬТЕТ', 70, 21)
INSERT INTO [dbo].[Faculties] ([Id], [Name], [Prestige], [HigherEducationInstitutionId]) VALUES (53, N'ФАКУЛЬТЕТ ПРАВА И ЭКОНОМИЧЕСКОЙ БЕЗОПАСНОСТИ', 60, 21)
INSERT INTO [dbo].[Faculties] ([Id], [Name], [Prestige], [HigherEducationInstitutionId]) VALUES (54, N'Исскуств', 70, 3)
INSERT INTO [dbo].[Faculties] ([Id], [Name], [Prestige], [HigherEducationInstitutionId]) VALUES (55, N'Геологический факультет', 60, 2)
INSERT INTO [dbo].[Faculties] ([Id], [Name], [Prestige], [HigherEducationInstitutionId]) VALUES (56, N'Высшая школа культурной политики и управления в гуманитарной сфере', 50, 2)
INSERT INTO [dbo].[Faculties] ([Id], [Name], [Prestige], [HigherEducationInstitutionId]) VALUES (57, N'Факультет психологии', 65, 2)
INSERT INTO [dbo].[Faculties] ([Id], [Name], [Prestige], [HigherEducationInstitutionId]) VALUES (58, N'ИНСТИТУТ ВОЕННО-ТЕХНИЧЕСКОГО ОБРАЗОВАНИЯ И БЕЗОПАСНОСТИ', 60, 17)
INSERT INTO [dbo].[Faculties] ([Id], [Name], [Prestige], [HigherEducationInstitutionId]) VALUES (59, N'ВЫСШАЯ ШКОЛА ЭКОНОМИКИ И МЕНЕДЖМЕНТА', 60, 17)
INSERT INTO [dbo].[Faculties] ([Id], [Name], [Prestige], [HigherEducationInstitutionId]) VALUES (60, N'ИНСТИТУТ ГОСУДАРСТВЕННОГО УПРАВЛЕНИЯ И ПРЕДПРИНИМАТЕЛЬСТВА', 60, 17)
INSERT INTO [dbo].[Faculties] ([Id], [Name], [Prestige], [HigherEducationInstitutionId]) VALUES (62, N'ИНСТИТУТ ГУМАНИТАРНЫХ НАУК И ИСКУССТВ', 60, 17)
INSERT INTO [dbo].[Faculties] ([Id], [Name], [Prestige], [HigherEducationInstitutionId]) VALUES (63, N'ИНСТИТУТ ЕСТЕСТВЕННЫХ НАУК', 60, 17)
INSERT INTO [dbo].[Faculties] ([Id], [Name], [Prestige], [HigherEducationInstitutionId]) VALUES (65, N' ИНСТИТУТ МАТЕМАТИКИ И КОМПЬЮТЕРНЫХ НАУК', 60, 17)
INSERT INTO [dbo].[Faculties] ([Id], [Name], [Prestige], [HigherEducationInstitutionId]) VALUES (68, N'ИНСТИТУТ МАТЕРИАЛОВЕДЕНИЯ И МЕТАЛЛУРГИИ', 60, 17)
INSERT INTO [dbo].[Faculties] ([Id], [Name], [Prestige], [HigherEducationInstitutionId]) VALUES (69, N'МЕХАНИКО-МАШИНОСТРОИТЕЛЬНЫЙ ИНСТИТУТ', 60, 17)
INSERT INTO [dbo].[Faculties] ([Id], [Name], [Prestige], [HigherEducationInstitutionId]) VALUES (70, N'ИНСТИТУТ РАДИОЭЛЕКТРОНИКИ И ИНФОРМАЦИОННЫХ ТЕХНОЛОГИЙ – РТФ', 60, 17)
INSERT INTO [dbo].[Faculties] ([Id], [Name], [Prestige], [HigherEducationInstitutionId]) VALUES (71, N'ИНСТИТУТ СОЦИАЛЬНЫХ И ПОЛИТИЧЕСКИХ НАУК', 60, 17)
INSERT INTO [dbo].[Faculties] ([Id], [Name], [Prestige], [HigherEducationInstitutionId]) VALUES (72, N'СТРОИТЕЛЬНЫЙ ИНСТИТУТ', 60, 17)
INSERT INTO [dbo].[Faculties] ([Id], [Name], [Prestige], [HigherEducationInstitutionId]) VALUES (73, N'ИНСТИТУТ ТЕХНОЛОГИЙ ОТКРЫТОГО ОБРАЗОВАНИЯ', 60, 17)
INSERT INTO [dbo].[Faculties] ([Id], [Name], [Prestige], [HigherEducationInstitutionId]) VALUES (74, N'УРАЛЬСКИЙ ЭНЕРГЕТИЧЕСКИЙ ИНСТИТУТ', 60, 17)
INSERT INTO [dbo].[Faculties] ([Id], [Name], [Prestige], [HigherEducationInstitutionId]) VALUES (75, N'ФИЗИКО-ТЕХНОЛОГИЧЕСКИЙ ИНСТИТУТ', 60, 17)
INSERT INTO [dbo].[Faculties] ([Id], [Name], [Prestige], [HigherEducationInstitutionId]) VALUES (76, N'ИНСТИТУТ ФИЗИЧЕСКОЙ КУЛЬТУРЫ, СПОРТА И МОЛОДЕЖНОЙ ПОЛИТИКИ', 60, 17)
INSERT INTO [dbo].[Faculties] ([Id], [Name], [Prestige], [HigherEducationInstitutionId]) VALUES (77, N'ИНСТИТУТ ФУНДАМЕНТАЛЬНОГО ОБРАЗОВАНИЯ', 60, 17)
INSERT INTO [dbo].[Faculties] ([Id], [Name], [Prestige], [HigherEducationInstitutionId]) VALUES (78, N'ХИМИКО-ТЕХНОЛОГИЧЕСКИЙ ИНСТИТУТ', 60, 17)
SET IDENTITY_INSERT [dbo].[Faculties] OFF
